## added prefixes for the ease of writing the queries.
PREFIX roxi: <http://pbonte.github.io/roxi/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
PREFIX saref: <https://saref.etsi.org/core/> 
PREFIX sioc: <http://www.w3.org/Submission/sioc-spec/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

### Write a query to find out "who is infected through close contact?"


### Write a query to find out "who is in which room with an infected person?"


### Write a query to get all of the values back.

# select ?s 
# where {
#     ?s ?p ?o .
# }