## added prefixes for the ease of writing the queries.
PREFIX : <http://pbonte.github.io/roxi/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
PREFIX saref: <https://saref.etsi.org/core/> 
PREFIX sioc: <http://www.w3.org/Submission/sioc-spec/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select * where {
    ?s ?p ?o
}

# Write a query to find out which person is infected with COVID and they are in which room.

# Comment / Remove the above query.


# Write a query to find out which person is close to the infected person.


# Comment / Remove the above query.



# After you have aligned the ontology for the location, write the query to find the location and the person.

