## added prefixes for the ease of writing the queries.
PREFIX : <http://pbonte.github.io/roxi/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
PREFIX saref: <https://saref.etsi.org/core/> 
PREFIX sioc: <http://www.w3.org/Submission/sioc-spec/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 


# Run the ?s ?p ?o query to see all the values returned from the stream

select * where {
    ?s ?p ?o .

}

# Delete this query
# Task 1: Write a query to find the location (?room) of the person (?person)



# Remember : You have to add the rules (in src/rules.n3 file) 
# to find the location. One rule for getting the location from SOSA 
# RFID sensor and another to align the facebook and RFID localisation.

# Delete the above query.
# Task 2: Write a query to find out the COVID positive person (?person) and 
# their location (?room)





# Delete the above query.
# Task 3: Write a query to find the person at risk of 
# COVID (?personAtRisk ) through contact tracing.




